modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="piseks_enderite"
version="2.1"
displayName="Pisek's Enderite 2"
credits="Source code: https://github.com/Piseks-Mods/Piseks-Enderite"
displayURL="https://github.com/Piseks-Mods/Fundys-Cursed-Food"
logoFile="logo.png"
authors="Písek Pískovec"
description='''
Mysterious metal from The Void dimension
'''

[[dependencies.piseks_enderite]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




